### ISSUE TITLE
capturing User stories, and Chef Inspec and OPA tests

### ISSUE THREAD

**Issue by mario-platt** [BlazingWind/OWASP-ASVS-4.0-testing-guide#1]
Some brilliant work here.
I had made a suggestion last year on main ASVS repo (https://github.com/OWASP/ASVS/issues/813) to start creating User Stories and associated validations with Chef Inspec and Open Policy Agent REGO policies (you currently have Python and ZAP scripts).
Would you consider hosting the associated User Stories as an element for each control ? I'd be happy to start submitting some PRs for that info.
I'll be doing a lot related to this in my company this year, so would expect to contributing OPA and User Stories

**Comment by BlazingWind** [comment]
As per our conversation on Twitter - I think it is a brilliant idea.

**Comment by BlazingWind** [comment]
The project is available in a separate repo under https://github.com/mario-platt/ASVS-Agile-Delivery-Guide
