### ISSUE TITLE
IMAP injection script is not valid python

### ISSUE THREAD

**Issue by umbernhard** [BlazingWind/OWASP-ASVS-4.0-testing-guide#7]
Attempting to run the IMAP injection test fails due to this line, which is not valid Python. 
https://github.com/BlazingWind/OWASP-ASVS-4.0-testing-guide/blob/b2afde651002822fa768fa484b8a3751521f927f/ZAP-scripts/active/5-2-3-imap-injection.py#L39

**Comment by BlazingWind** [comment]
Thank you for raising the issue @umbernhard
Fixed in #9

**Comment by umbernhard** [comment]
Thanks @BlazingWind! Sorry to continue to be a bother, but looking at the fix, is this really supposed to be an append? It seems to me that if any of the elements earlier in the sequence get stripped or denied by the target, then if they appear again with new elements wouldn't you get a false negative? 
https://github.com/BlazingWind/OWASP-ASVS-4.0-testing-guide/blob/1f680d2e981c9baaa0b7dd5c94be9f3b214a3c17/ZAP-scripts/active/5-2-3-imap-injection.py#L40

**Comment by BlazingWind** [comment]
That's a good point, I see that it could happen. Fixed in https://github.com/BlazingWind/OWASP-ASVS-4.0-testing-guide/commit/e81280268c837824f9e81e90053a909451a79dad

**Comment by umbernhard** [comment]
Awesome, thank you!
